#ifndef __PROJECT_CONF_H
#define __PROJECT_CONF_H

#define LOG_LEVEL_HEART_RATE_SENSOR LOG_LEVEL_INFO
#define LOG_LEVEL_BLOOD_PRESSURE_SENSOR LOG_LEVEL_INFO
#define LOG_LEVEL_TEMPERATURE_SENSOR LOG_LEVEL_INFO
#define LOG_LEVEL_RESPIRATION_SENSOR LOG_LEVEL_INFO
#define LOG_LEVEL_OXYGEN_SATURATION_SENSOR LOG_LEVEL_INFO
#define LOG_LEVEL_MQTT_MONITOR LOG_LEVEL_DBG
#define LOG_LEVEL_ALARM_SYSTEM LOG_LEVEL_INFO

#undef IEEE802154_CONF_PANID
#define IEEE802154_CONF_PANID 0x0041

#define UIP_CONF_TCP 1

#endif /* __PROJECT_CONF_H */
